// Package generator creates standalone, runnable Go code snippets that demonstrate
// how to retrieve secrets from HashiCorp Vault using pure Go standard library (net/http).
package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

// StructField represents a typed field within a generated Go struct.
type StructField struct {
	Name    string
	Type    string
	JSONKey string
}

// StructDef represents a generated Go struct definition for a nested JSON key.
type StructDef struct {
	KeyName  string
	TypeName string
	VarName  string
	Fields   []StructField
}

// TemplateData holds the parameters passed into the text/template code generator.
type TemplateData struct {
	VaultAddr string
	Mount     string
	Path      string
	Structs   []StructDef
	PlainKeys []string
}

const retrievalGoTemplate = `// Code generated by Vault TUI. DO NOT EDIT.
// This standalone program demonstrates how to retrieve the Vault secret:
// Mount: {{ .Mount }}
// Path:  {{ .Path }}
//
// Prerequisites:
//   export VAULT_ADDR="{{ .VaultAddr }}"
//   export VAULT_TOKEN="<your-vault-token>"
//
// Run:
//   go run main.go

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// VaultKVV2Response represents the standard Vault KV v2 secret response envelope.
type VaultKVV2Response struct {
	RequestID string {{ jsonTag "request_id" }}
	Data      struct {
		Data     map[string]interface{} {{ jsonTag "data" }}
		Metadata struct {
			CreatedTime  string {{ jsonTag "created_time" }}
			DeletionTime string {{ jsonTag "deletion_time" }}
			Destroyed    bool   {{ jsonTag "destroyed" }}
			Version      int    {{ jsonTag "version" }}
		} {{ jsonTag "metadata" }}
	} {{ jsonTag "data" }}
}
{{- if .Structs }}

// --- Structured Key Types ---
{{- range .Structs }}

// {{ .TypeName }} represents the structured JSON payload for key {{ printf "%q" .KeyName }}.
type {{ .TypeName }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }} {{ jsonTag .JSONKey }}
{{- end }}
}
{{- end }}
{{- end }}

func main() {
	// 1. Resolve Vault address and authentication token
	vaultAddr := os.Getenv("VAULT_ADDR")
	if vaultAddr == "" {
		vaultAddr = "{{ .VaultAddr }}"
	}
	vaultAddr = strings.TrimRight(vaultAddr, "/")

	vaultToken := os.Getenv("VAULT_TOKEN")
	if vaultToken == "" {
		fmt.Fprintln(os.Stderr, "Error: VAULT_TOKEN environment variable is required")
		os.Exit(1)
	}

	mount := "{{ .Mount }}"
	secretPath := "{{ .Path }}"
	reqURL := fmt.Sprintf("%s/v1/%s/data/%s", vaultAddr, mount, secretPath)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// 2. Build HTTP GET request using Go standard library
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, reqURL, nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create HTTP request: %v\n", err)
		os.Exit(1)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Vault-Token", vaultToken)

	// 3. Execute HTTP request
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "HTTP request failed: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		fmt.Fprintf(os.Stderr, "Vault returned status %d: %s\n", resp.StatusCode, string(body))
		os.Exit(1)
	}

	// 4. Decode Vault envelope
	var vaultResp VaultKVV2Response
	if err := json.NewDecoder(resp.Body).Decode(&vaultResp); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to decode JSON response: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Successfully retrieved secret '%s' (Version: %d)\n", secretPath, vaultResp.Data.Metadata.Version)
	fmt.Printf("  Created: %s\n\n", vaultResp.Data.Metadata.CreatedTime)

	// 5. Access secret key-value pairs
{{- range .Structs }}

	// Parse structured key: {{ .KeyName }}
	if rawVal, ok := vaultResp.Data.Data["{{ .KeyName }}"]; ok {
		var {{ .VarName }} {{ .TypeName }}
		var jsonBytes []byte
		switch v := rawVal.(type) {
		case string:
			jsonBytes = []byte(v)
		default:
			jsonBytes, _ = json.Marshal(v)
		}
		if err := json.Unmarshal(jsonBytes, &{{ .VarName }}); err != nil {
			fmt.Printf("  {{ .KeyName }} (raw): %v\n", rawVal)
		} else {
			fmt.Printf("  {{ .KeyName }} (decoded): %+v\n", {{ .VarName }})
		}
	}
{{- end }}
{{- range .PlainKeys }}

	if val, ok := vaultResp.Data.Data["{{ . }}"]; ok {
		fmt.Printf("  {{ . }}: %v\n", val)
	}
{{- end }}
}
`

// GenerateGoRetrievalCode produces a complete, runnable Go source file that fetches
// and decodes a specific secret from Vault using text/template.
func GenerateGoRetrievalCode(vaultAddr, mount, path string, secretData map[string]string) string {
	if vaultAddr == "" {
		vaultAddr = "http://10.0.0.180:8200"
	}
	if mount == "" {
		mount = "secret"
	}

	cleanPath := strings.Trim(path, "/")
	structs, plainKeys := buildTemplateDataKeys(secretData)

	data := TemplateData{
		VaultAddr: vaultAddr,
		Mount:     mount,
		Path:      cleanPath,
		Structs:   structs,
		PlainKeys: plainKeys,
	}

	funcMap := template.FuncMap{
		"jsonTag": func(k string) string {
			return fmt.Sprintf("`json:\"%s\"`", k)
		},
	}

	tmpl, err := template.New("retrieval").Funcs(funcMap).Parse(retrievalGoTemplate)
	if err != nil {
		return fmt.Sprintf("// Template parse error: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Sprintf("// Template execute error: %v", err)
	}

	return buf.String()
}

func buildTemplateDataKeys(secretData map[string]string) ([]StructDef, []string) {
	var structs []StructDef
	var plainKeys []string

	keys := make([]string, 0, len(secretData))
	for k := range secretData {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		val := secretData[k]
		if isJSONString(val) {
			var parsed map[string]interface{}
			if err := json.Unmarshal([]byte(val), &parsed); err == nil && len(parsed) > 0 {
				typeName := toPascalCase(k) + "Config"
				varName := toCamelCase(k)

				subKeys := make([]string, 0, len(parsed))
				for sk := range parsed {
					subKeys = append(subKeys, sk)
				}
				sort.Strings(subKeys)

				var fields []StructField
				for _, sk := range subKeys {
					fields = append(fields, StructField{
						Name:    toPascalCase(sk),
						Type:    inferGoType(parsed[sk]),
						JSONKey: sk,
					})
				}

				structs = append(structs, StructDef{
					KeyName:  k,
					TypeName: typeName,
					VarName:  varName,
					Fields:   fields,
				})
				continue
			}
		}

		plainKeys = append(plainKeys, k)
	}

	return structs, plainKeys
}

func inferGoType(val interface{}) string {
	switch val.(type) {
	case float64:
		f := val.(float64)
		if f == float64(int(f)) {
			return "int"
		}
		return "float64"
	case bool:
		return "bool"
	default:
		return "string"
	}
}

func isJSONString(s string) bool {
	trimmed := strings.TrimSpace(s)
	if !strings.HasPrefix(trimmed, "{") || !strings.HasSuffix(trimmed, "}") {
		return false
	}
	return json.Valid([]byte(trimmed))
}

// SanitizeFilename creates a safe filename from a secret path.
func SanitizeFilename(path string) string {
	clean := strings.Trim(path, "/")
	re := regexp.MustCompile(`[^a-zA-Z0-9_\-]+`)
	safe := re.ReplaceAllString(clean, "_")
	if safe == "" {
		safe = "secret"
	}
	return "get_" + safe + ".go"
}

// SaveRetrievalFile writes the generated Go code to the target directory.
func SaveRetrievalFile(dir, filename, code string) (string, error) {
	if dir == "" {
		dir = "examples"
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	filePath := filepath.Join(dir, filename)
	if err := os.WriteFile(filePath, []byte(code), 0644); err != nil {
		return "", err
	}
	return filePath, nil
}

func toPascalCase(s string) string {
	parts := regexp.MustCompile(`[^a-zA-Z0-9]+`).Split(s, -1)
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	res := sb.String()
	if res == "" {
		return "Field"
	}
	return res
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return "field"
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}
