// Package generator creates standalone, runnable Go code snippets that demonstrate
// how to retrieve secrets from HashiCorp Vault using pure Go standard library (net/http).
package generator

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// GenerateGoRetrievalCode produces a complete, runnable Go source file that fetches
// and decodes a specific secret from Vault using only standard library packages.
func GenerateGoRetrievalCode(vaultAddr, mount, path string, secretData map[string]string) string {
	if vaultAddr == "" {
		vaultAddr = "http://10.0.0.180:8200"
	}
	if mount == "" {
		mount = "secret"
	}

	cleanPath := strings.Trim(path, "/")
	structDefs := generateNestedStructs(secretData)

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`// Code generated by Vault TUI. DO NOT EDIT.
// This standalone program demonstrates how to retrieve the Vault secret:
// Mount: %s
// Path:  %s
//
// Prerequisites:
//   export VAULT_ADDR="%s"
//   export VAULT_TOKEN="<your-vault-token>"
//
// Run:
//   go run main.go

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// VaultKVV2Response represents the standard Vault KV v2 secret response envelope.
type VaultKVV2Response struct {
	RequestID string `+"`json:\"request_id\"`"+`
	Data      struct {
		Data     map[string]interface{} `+"`json:\"data\"`"+`
		Metadata struct {
			CreatedTime  string `+"`json:\"created_time\"`"+`
			DeletionTime string `+"`json:\"deletion_time\"`"+`
			Destroyed    bool   `+"`json:\"destroyed\"`"+`
			Version      int    `+"`json:\"version\"`"+`
		} `+"`json:\"metadata\"`"+`
	} `+"`json:\"data\"`"+`
}
`, mount, cleanPath, vaultAddr))

	if structDefs != "" {
		sb.WriteString("\n// --- Structured Key Types ---\n")
		sb.WriteString(structDefs)
	}

	sb.WriteString(fmt.Sprintf(`
func main() {
	// 1. Resolve Vault address and authentication token
	vaultAddr := os.Getenv("VAULT_ADDR")
	if vaultAddr == "" {
		vaultAddr = "%s"
	}
	vaultAddr = strings.TrimRight(vaultAddr, "/")

	vaultToken := os.Getenv("VAULT_TOKEN")
	if vaultToken == "" {
		fmt.Fprintln(os.Stderr, "Error: VAULT_TOKEN environment variable is required")
		os.Exit(1)
	}

	mount := "%s"
	secretPath := "%s"
	reqURL := fmt.Sprintf("%%s/v1/%%s/data/%%s", vaultAddr, mount, secretPath)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// 2. Build HTTP GET request using Go standard library
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, reqURL, nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create HTTP request: %%v\n", err)
		os.Exit(1)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Vault-Token", vaultToken)

	// 3. Execute HTTP request
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "HTTP request failed: %%v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		fmt.Fprintf(os.Stderr, "Vault returned status %%d: %%s\n", resp.StatusCode, string(body))
		os.Exit(1)
	}

	// 4. Decode Vault envelope
	var vaultResp VaultKVV2Response
	if err := json.NewDecoder(resp.Body).Decode(&vaultResp); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to decode JSON response: %%v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Successfully retrieved secret '%%s' (Version: %%d)\n", secretPath, vaultResp.Data.Metadata.Version)
	fmt.Printf("  Created: %%s\n\n", vaultResp.Data.Metadata.CreatedTime)

	// 5. Access secret key-value pairs
`, vaultAddr, mount, cleanPath))

	// Generate parsing/printing logic for keys
	keys := make([]string, 0, len(secretData))
	for k := range secretData {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		val := secretData[k]
		if isJSONString(val) {
			typeName := toPascalCase(k) + "Config"
			sb.WriteString(fmt.Sprintf(`	// Parse structured key: %s
	if rawVal, ok := vaultResp.Data.Data["%s"]; ok {
		var %s %s
		var jsonBytes []byte
		switch v := rawVal.(type) {
		case string:
			jsonBytes = []byte(v)
		default:
			jsonBytes, _ = json.Marshal(v)
		}
		if err := json.Unmarshal(jsonBytes, &%s); err != nil {
			fmt.Printf("  %s (raw): %%v\n", rawVal)
		} else {
			fmt.Printf("  %s (decoded): %%+v\n", %s)
		}
	}
`, k, k, toCamelCase(k), typeName, toCamelCase(k), k, k, toCamelCase(k)))
		} else {
			sb.WriteString(fmt.Sprintf(`	if val, ok := vaultResp.Data.Data["%s"]; ok {
		fmt.Printf("  %s: %%v\n", val)
	}
`, k, k))
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// generateNestedStructs generates Go struct definitions for any JSON strings in the secret data.
func generateNestedStructs(secretData map[string]string) string {
	var sb strings.Builder
	keys := make([]string, 0, len(secretData))
	for k := range secretData {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		val := secretData[k]
		if !isJSONString(val) {
			continue
		}

		var parsed map[string]interface{}
		if err := json.Unmarshal([]byte(val), &parsed); err != nil || len(parsed) == 0 {
			continue
		}

		typeName := toPascalCase(k) + "Config"
		sb.WriteString(fmt.Sprintf("// %s represents the structured JSON payload for key %q.\ntype %s struct {\n", typeName, k, typeName))

		subKeys := make([]string, 0, len(parsed))
		for sk := range parsed {
			subKeys = append(subKeys, sk)
		}
		sort.Strings(subKeys)

		for _, sk := range subKeys {
			fieldName := toPascalCase(sk)
			goType := inferGoType(parsed[sk])
			sb.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, sk))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func inferGoType(val interface{}) string {
	switch val.(type) {
	case float64:
		// Check if it's an integer
		f := val.(float64)
		if f == float64(int(f)) {
			return "int"
		}
		return "float64"
	case bool:
		return "bool"
	default:
		return "string"
	}
}

func isJSONString(s string) bool {
	trimmed := strings.TrimSpace(s)
	if !strings.HasPrefix(trimmed, "{") || !strings.HasSuffix(trimmed, "}") {
		return false
	}
	return json.Valid([]byte(trimmed))
}

// SanitizeFilename creates a safe filename from a secret path.
func SanitizeFilename(path string) string {
	clean := strings.Trim(path, "/")
	re := regexp.MustCompile(`[^a-zA-Z0-9_\-]+`)
	safe := re.ReplaceAllString(clean, "_")
	if safe == "" {
		safe = "secret"
	}
	return "get_" + safe + ".go"
}

// SaveRetrievalFile writes the generated Go code to the target directory.
func SaveRetrievalFile(dir, filename, code string) (string, error) {
	if dir == "" {
		dir = "examples"
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	filePath := filepath.Join(dir, filename)
	if err := os.WriteFile(filePath, []byte(code), 0644); err != nil {
		return "", err
	}
	return filePath, nil
}

func toPascalCase(s string) string {
	parts := regexp.MustCompile(`[^a-zA-Z0-9]+`).Split(s, -1)
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	res := sb.String()
	if res == "" {
		return "Field"
	}
	return res
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return "field"
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}
